# Generated by Django 6.0 on 2026-07-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
